import type { MergedDraft } from '../types.js'
import { buildAnalystPrompt } from './analyst-prompt.js'
import { buildDecomposerPrompt } from './decomposer-prompt.js'
import { buildSharedPreamble } from './shared-preamble.js'
import { buildSynthesizerPrompt } from './synthesizer-prompt.js'

export interface CompilePromptsParams {
  draft: MergedDraft
  runId: string
}

export interface CompiledPrompts {
  shared: string
  decomposer: string
  analyst: string
  synthesizer: string
}

/**
 * Pure function: merge draft → 4 prompt strings.
 * No IO. CLI (cli-compile.ts) handles file reads/writes.
 */
export function compilePrompts(p: CompilePromptsParams): CompiledPrompts {
  const sharedPreamble = buildSharedPreamble(p.draft)
  const params = { draft: p.draft, sharedPreamble }
  return {
    shared: sharedPreamble,
    decomposer: buildDecomposerPrompt(params),
    analyst: buildAnalystPrompt(params),
    synthesizer: buildSynthesizerPrompt(params),
  }
}

export interface RenderSystemTsFileParams {
  exportName: string
  promptBody: string
  header: string
  imports?: string[]
}

/**
 * Render a TS file with AUTO-GENERATED header + named const export.
 * Properly escapes backticks and ${} in promptBody to prevent template literal breakage.
 */
export function renderSystemTsFile(args: RenderSystemTsFileParams): string {
  const importLines = (args.imports ?? []).map(i => `import ${i}`).join('\n')
  const prefix = importLines ? `${importLines}\n\n` : ''
  return `${args.header}\n\n${prefix}export const ${args.exportName} = \`${escapeBacktick(args.promptBody)}\`\n`
}

export interface RenderHeaderParams {
  runId: string
  sources: { slug: string, refUrl?: string }[]
  generatedAt: string
}

/**
 * AUTO-GENERATED header for agent .system.ts files.
 * Lists source slugs + URLs for traceability.
 */
export function renderHeaderForAgentFile(args: RenderHeaderParams): string {
  const lines: string[] = []
  lines.push(`// AUTO-GENERATED by worker prompt-research-compile at ${args.generatedAt}`)
  lines.push(`// DO NOT EDIT — regenerate via prompt:compile; 人工取捨在 promote 時進行`)
  lines.push(`//`)
  lines.push(`// Frames derived from:`)
  for (const s of args.sources) {
    if (s.refUrl)
      lines.push(`//   - ${s.slug.padEnd(40)} (${s.refUrl})`)
    else lines.push(`//   - ${s.slug}`)
  }
  lines.push(`//`)
  lines.push(`// Run ID: ${args.runId}`)
  return lines.join('\n')
}

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}
