import type { AnalystFrame, Digest, MergedDraft, SourceSpec } from './types.js'
import { distance } from 'fastest-levenshtein'
import { MergedDraftSchema } from './types.js'

// 用 normalized Levenshtein ratio (1 - distance / maxLen)
// 0.6 比舊 Sørensen-Dice 的 0.7 寬鬆一格、因為 Levenshtein 對短字串較嚴
// (例：'央行升息時' vs '當央行升息' Dice=0.75 / Lev ratio=0.6)
const FUZZY_THRESHOLD = 0.6

function similarityRatio(a: string, b: string): number {
  const maxLen = Math.max(a.length, b.length)
  if (maxLen === 0)
    return 1
  return 1 - distance(a, b) / maxLen
}

export function normalizeKey(s: string): string {
  return s
    .toLowerCase()
    .replace(/[!?.,;:'"(){}[\]<>]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

interface FrameWithSource { from: string, frame: AnalystFrame }
export interface FrameGroup { group: string, frames: FrameWithSource[] }

export function mergeFrames(digests: readonly Digest[]): FrameGroup[] {
  const groups: FrameGroup[] = []
  for (const d of digests) {
    for (const frame of d.analystFrames) {
      const key = normalizeKey(frame.whenToApply)
      const match = groups.find((g) => {
        const gKey = normalizeKey(g.group)
        if (gKey === key)
          return true
        return similarityRatio(gKey, key) >= FUZZY_THRESHOLD
      })
      if (match)
        match.frames.push({ from: d.sourceSlug, frame })
      else groups.push({ group: frame.whenToApply, frames: [{ from: d.sourceSlug, frame }] })
    }
  }
  return groups
}

export interface MergedVocabularyItem {
  preferred: string
  avoid: string[]
  reason: string
}

export function mergeVocabulary(digests: readonly Digest[]): MergedVocabularyItem[] {
  const byPreferred = new Map<string, { avoid: Set<string>, reasons: string[] }>()
  for (const d of digests) {
    for (const v of d.vocabulary) {
      const existing = byPreferred.get(v.preferred) ?? { avoid: new Set(), reasons: [] }
      for (const a of v.avoid) existing.avoid.add(a)
      if (v.reason && !existing.reasons.includes(v.reason))
        existing.reasons.push(v.reason)
      byPreferred.set(v.preferred, existing)
    }
  }
  return Array.from(byPreferred, ([preferred, { avoid, reasons }]) => ({
    preferred,
    avoid: Array.from(avoid).sort(),
    reason: reasons.join('; '),
  }))
}

export interface MergedCompliance {
  // rule テキストを重複排除して集約する（id は merger 段階では不要）
  redFlags: string[]
  disclaimers: string[]
}

export function mergeCompliance(digests: readonly Digest[]): MergedCompliance {
  const redFlagRules = new Set<string>()
  const disclaimers: string[] = []
  for (const d of digests) {
    if (!d.compliance)
      continue
    for (const f of d.compliance.redFlags) redFlagRules.add(f.rule)
    if (d.compliance.suggestedDisclaimer && !disclaimers.includes(d.compliance.suggestedDisclaimer)) {
      disclaimers.push(d.compliance.suggestedDisclaimer)
    }
  }
  return { redFlags: Array.from(redFlagRules), disclaimers }
}

export function renderMergedMarkdown(
  digests: readonly Digest[],
  generatedAt: string,
): string {
  const frameGroups = mergeFrames(digests)
  const vocab = mergeVocabulary(digests)
  const compliance = mergeCompliance(digests)
  const sourceList = digests.map(d => d.sourceSlug).join(', ')

  const partA = frameGroups.map((g) => {
    const framesBlock = g.frames.map(({ from, frame }) => {
      const questions = frame.questions.map((q, i) => `    ${i + 1}. ${q} (from: ${from})`).join('\n')
      return `- [from: ${from}] **${frame.name}**
  description: ${frame.description}
  questions:
${questions}`
    }).join('\n')
    return `### ${g.group}\n${framesBlock}`
  }).join('\n\n')

  const partB = vocab.length === 0
    ? '(no vocabulary)'
    : ['Preferred | Avoid | Reason', '----------|-------|-------', ...vocab.map(v => `${v.preferred} | ${v.avoid.join(', ')} | ${v.reason}`)].join('\n')

  const partC = compliance.redFlags.length === 0
    ? '(no red flags)'
    : compliance.redFlags.map(f => `- ${f}`).join('\n')

  const partD = `(工程師手編區——以下為 stub、請 review + 改寫後貼進 apps/server/src/prompts/*.prompt.ts 對應檔)

\`\`\`
你是一個財經新聞分析師、依據以下分析框架處理新聞事件。

[frames]
${frameGroups.map(g => `- ${g.group}: ${g.frames.map(f => f.frame.name).join(' / ')}`).join('\n')}

[合規紅線]
${compliance.redFlags.map(f => `- ${f}`).join('\n')}
\`\`\``

  const partE = digests.map((d) => {
    const ref = d.rawSourceRef
    const refStr = ref.url ?? ref.localPath ?? '(unknown)'
    const sha = ref.commitSha ? ` @ ${ref.commitSha}` : ''
    return `- ${d.sourceSlug}: ${refStr}${sha}`
  }).join('\n')

  return `# Analyzer Prompt Draft (${generatedAt.slice(0, 10)})

> Generated by worker prompt-research at ${generatedAt}
> Sources: ${sourceList}

## Part A: Analyst Frames (merged)

${partA}

## Part B: Vocabulary (merged)

${partB}

## Part C: Compliance Red Flags

${partC}

## Part D: Suggested Analyzer System Prompt (工程師編輯基礎)

${partD}

## Part E: Raw Source Refs

${partE}
`
}

export interface MergeResult {
  markdown: string
  draft: MergedDraft
}

/**
 * 合併多份 Digest，同時輸出 markdown (人讀) + 結構化 draft JSON (程式讀)。
 * markdown 內容與既有 renderMergedMarkdown 完全相同。
 */
export function mergeDigests(digests: Digest[], opts?: { sources?: SourceSpec[] }): MergeResult {
  const generatedAt = new Date().toISOString()

  // --- markdown path (既有行為保留) ---
  const markdown = renderMergedMarkdown(digests, generatedAt)

  // --- draft path ---
  const frameGroups = mergeFrames(digests)

  // frames: 每個 group 裡的每個 frame 攜帶 sourceSlug + id
  const draftFrames = frameGroups.map(g => ({
    groupKey: g.group,
    items: g.frames.map(({ from, frame }) => ({
      id: frame.id,
      sourceSlug: from,
      frame,
    })),
  }))

  // vocabulary: 保留 per-source 記錄 (不做 dedupe、給 compiler 自行處理)
  const draftVocabulary = digests.flatMap(d =>
    d.vocabulary.map(entry => ({
      id: entry.id,
      sourceSlug: d.sourceSlug,
      entry,
    })),
  )

  // redFlags: 保留 per-source 記錄 (含 id + sourceSlug)
  const draftRedFlags = digests.flatMap(d =>
    (d.compliance?.redFlags ?? []).map(entry => ({
      id: entry.id,
      sourceSlug: d.sourceSlug,
      entry,
    })),
  )

  // rawSourceRefs
  const draftRawSourceRefs = digests.map(d => ({
    sourceSlug: d.sourceSlug,
    ref: {
      url: d.rawSourceRef.url,
      localPath: d.rawSourceRef.localPath,
      commitSha: d.rawSourceRef.commitSha,
    },
  }))

  // sources: 從 opts 或從 digests 推導
  const sources: SourceSpec[] = opts?.sources ?? []

  const rawDraft = {
    generatedAt,
    sources,
    frames: draftFrames,
    vocabulary: draftVocabulary,
    redFlags: draftRedFlags,
    rawSourceRefs: draftRawSourceRefs,
  }

  const draft = MergedDraftSchema.parse(rawDraft)

  return { markdown, draft }
}
